apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mongodb
    component: config-server
    replica-name: config0
  name: mongodb-config0-configmap
  namespace: mongodb
data:
  mongod.conf: |-
    replication:
      replSetName: config0
    sharding:
      clusterRole: configsvr

