apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mongodb
    component: shard-server
    replica-name: shard0
  name: mongodb-shard0-configmap
  namespace: mongodb
data:
  mongod.conf: |
    replication:
      replSetName: shard00
    sharding:
      clusterRole: shardsvr    
