apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: mongodb
    component: shard-server
    replica-name: shard1
  name: mongodb-shard1-service-client
  namespace: mongodb
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mongodb
      port: 27017
  selector:
    app: mongodb
    component: shard-server
    replica-name: shard1 
