apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: mongodb
    component: mongos
  name: mongos
  namespace:  mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        component: mongos
    spec:
      containers:
        - name: mongos
          image: mongo:4.2.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongodb
              containerPort: 27017
          command:
            - mongos
            - --configdb=config0/mongodb-config0-0.mongodb-config0-service:27017,mongodb-config0-1.mongodb-config0-service:27017,mongodb-config0-2.mongodb-config0-service:27017
            - --port=27017
            - --bind_ip=0.0.0.0
