apiVersion: v1
kind: Service
metadata:
  name: mongos
  namespace: mongodb
  labels:
    app: mongodb
    component: mongos
spec:
  type: NodePort
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
    component: mongos
